### ISSUE TITLE
Support for source translaters

### ISSUE THREAD

**Issue by SonnyX** [doutatsu/kenmei#73]
Are there long-term plans to support other websites as trackr.moe did?

**Comment by doutatsu** [comment]
> Are there long-term plans to support other websites as trackr.moe did?

Of course @SonnyX, that's why its a **cross-site** manga tracker. I started with MangaDex, as its the most used source based on the poll I ran and it's easiest to implement. Now that its fully working, I plan to do another poll to see which is the next most popular manga source and start working on that
