### ISSUE TITLE
Incorrect latest chapter

### ISSUE THREAD

**Issue by Weefsat** [doutatsu/kenmei#80]
My Home Hero doesn't display the correct last chapter, Instead, it displays a chapter that doesn't exist. 
![Untitled](https://user-images.githubusercontent.com/39443093/68401907-d0445b00-017a-11ea-8a67-f8fd52fdfdea.png)
https://mangadex.org/manga/36496

**Comment by doutatsu** [comment]
@Weefsat Hm, this is an annoying one. I suspect this was due to someone uploading a chapter, us grabbing that as the latest chapter, but then it got deleted. 

But because I update the series only after a new one comes out, these data inconsistencies could get persisted for awhile, which is not good. I've now updated the series, so you get the righr chapter, but I'll have to think how to fix this.

For perfomance reasons, I avoid updating all the series we've got, instead actually monitoring latest releases. But there is no monitoring to be done on any update of the series, like if a chapter got removed or lets say a series title being uploaded with a typo, but then updated. 

I'll close this for now, but will add my own ticket for myself to try and come up with a solution to address this.

**Comment by Weefsat** [comment]
I think this can be solved in most cases with the ignore latest chapter feature.

**Comment by doutatsu** [comment]
> I think this can be solved in most cases with the ignore latest chapter feature. Happened all the time in trackr.moe too.

I am aware of that, but I find it to be an avoidance of the problem, which could be solved more cleverly. I rather make sure our data is in a good shape as much as possible, but I can see that something like this might become neccecary. I was more interested in crowdsourcing this information instead of having per user chapter ignore.
