### ISSUE TITLE
Incorrect label of oneshot

### ISSUE THREAD

**Issue by Weefsat** [doutatsu/kenmei#88]
A short Yandere manga is labeled as unknown chapter instead of oneshot. It was labeled as oneshot before, but changed today.
![Untitled](https://user-images.githubusercontent.com/39443093/68524179-da25a580-02c3-11ea-8204-decfa275eb93.png)
https://mangadex.org/manga/37591

**Comment by doutatsu** [comment]
This is expected behaviour. Yesterday, I've added improvement for chapters, that MangaDex doesn't have any information on (chapter or title wise). MangaDex themselves use `Oneshot` as their own default value for such chapters, but they don't know either if it is a oneshot or not. I don't think it's the correct way to categorise, hence I show them as **Unknown Chapter** instead.

Now, the reason that you had a Oneshot before (instead of nothing, as such series would have been shown before), is because there was a correctly titled series uploaded as Oneshot before. But then the latest one to be uploaded is this chapter, which doesn't have any info, but MangaDex still marks it as Oneshot. I am not sure why the other one doesn't even show up, even though I can see it by asking the API.
